export const GET_RUN_CONFIG_QAM_TABLE_STARTED = 'GET_RUN_CONFIG_QAM_TABLE_STARTED';
export const GET_RUN_CONFIG_QAM_TABLE_SUCCEEDED = 'GET_RUN_CONFIG_QAM_TABLE_SUCCEEDED';
export const GET_RUN_CONFIG_QAM_TABLE_FAILED = 'GET_RUN_CONFIG_QAM_TABLE_FAILED';

export const GET_RC_QAM_CREATE_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_CREATE_TABLE_ROW_SUCCEEDED';
export const GET_RC_QAM_DELETE_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_DELETE_TABLE_ROW_SUCCEEDED';
export const GET_RC_QAM_EDIT_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_EDIT_TABLE_ROW_SUCCEEDED';

export const GET_MANAGE_CONFIG_QAM_TABLE_STARTED = 'GET_MANAGE_CONFIG_QAM_TABLE_STARTED';
export const GET_MANAGE_CONFIG_QAM_TABLE_SYSTEM_SUCCEEDED = 'GET_MANAGE_CONFIG_QAM_TABLE_SYSTEM_SUCCEEDED';
export const GET_MANAGE_CONFIG_QAM_TABLE_USER_SUCCEEDED = 'GET_MANAGE_CONFIG_QAM_TABLE_USER_SUCCEEDED';
export const GET_MANAGE_CONFIG_QAM_TABLE_FAILED = 'GET_MANAGE_CONFIG_QAM_TABLE_FAILED';

export const SHOW_POP_UP = 'SHOW_POP_UP';
export const HIDE_POP_UP = 'HIDE_POP_UP';

export const POST_CONFIG_QAM_TABLE_ADD_RANGE = 'POST_CONFIG_QAM_TABLE_ADD_RANGE';
export const GET_MANAGE_NEW_DATABASE_ADD_SUCCEEDED = 'GET_MANAGE_NEW_DATABASE_ADD_SUCCEEDED';






