export const GET_RUN_CONFIG_QAM_TABLE_STARTED = 'GET_RUN_CONFIG_QAM_TABLE_STARTED';
export const GET_RUN_CONFIG_QAM_TABLE_SUCCEEDED = 'GET_RUN_CONFIG_QAM_TABLE_SUCCEEDED';
export const GET_RUN_CONFIG_QAM_TABLE_FAILED = 'GET_RUN_CONFIG_QAM_TABLE_FAILED';

export const GET_RC_QAM_CREATE_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_CREATE_TABLE_ROW_SUCCEEDED';
export const GET_RC_QAM_DELETE_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_DELETE_TABLE_ROW_SUCCEEDED';
export const GET_RC_QAM_EDIT_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_EDIT_TABLE_ROW_SUCCEEDED';


