export const GET_RUN_CONFIG_QAM_TABLE_STARTED = 'GET_RUN_CONFIG_QAM_TABLE_STARTED';
export const GET_RUN_CONFIG_QAM_TABLE_SUCCEEDED = 'GET_RUN_CONFIG_QAM_TABLE_SUCCEEDED';
export const GET_RUN_CONFIG_QAM_TABLE_FAILED = 'GET_RUN_CONFIG_QAM_TABLE_FAILED';

export const GET_RC_QAM_CREATE_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_CREATE_TABLE_ROW_SUCCEEDED';
export const GET_RC_QAM_DELETE_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_DELETE_TABLE_ROW_SUCCEEDED';
export const GET_RC_QAM_EDIT_TABLE_ROW_SUCCEEDED = 'GET_RC_QAM_EDIT_TABLE_ROW_SUCCEEDED';

export const GET_RUN_CONFIG_SINGLE_QAM_TABLE_STARTED = 'GET_RUN_CONFIG_SINGLE_QAM_TABLE_STARTED';
export const GET_RUN_CONFIG_SINGLE_QAM_TABLE_SUCCEEDED = 'GET_RUN_CONFIG_SINGLE_QAM_TABLE_SUCCEEDED';
export const GET_RUN_CONFIG_SINGLE_QAM_TABLE_FAILED = 'GET_RUN_CONFIG_SINGLE_QAM_TABLE_FAILED';


export const SHOW_POP_UP = 'SHOW_POP_UP';
export const HIDE_POP_UP = 'HIDE_POP_UP';

export const POST_SPLIT_SUCCEEDED = 'POST_SPLIT_SUCCEEDED';
export const POST_ANNEX_SUCCEEDED = 'POST_ANNEX_SUCCEEDED';

export const GET_SPLIT_STARTED = 'GET_SPLIT_STARTED';
export const GET_SPLIT_SUCCEEDED = 'GET_SPLIT_SUCCEEDED';
export const GET_SPLIT_FAILED = 'GET_SPLIT_FAILED';

export const GET_ANNEX_STARTED = 'GET_ANNEX_STARTED';
export const GET_ANNEX_SUCCEEDED = 'GET_ANNEX_SUCCEEDED';
export const GET_ANNEX_FAILED = 'GET_ANNEX_FAILED';

export const GET_MANAGE_CONFIG_QAM_TABLE_STARTED = 'GET_MANAGE_CONFIG_QAM_TABLE_STARTED';
export const GET_MANAGE_CONFIG_QAM_TABLE_SYSTEM_SUCCEEDED = 'GET_MANAGE_CONFIG_QAM_TABLE_SYSTEM_SUCCEEDED';
export const GET_MANAGE_CONFIG_QAM_TABLE_USER_SUCCEEDED = 'GET_MANAGE_CONFIG_QAM_TABLE_USER_SUCCEEDED';
export const GET_MANAGE_CONFIG_QAM_TABLE_FAILED = 'GET_MANAGE_CONFIG_QAM_TABLE_FAILED';
export const GET_MANAGE_NEW_DATABASE_ADD_SUCCEEDED = 'GET_MANAGE_NEW_DATABASE_ADD_SUCCEEDED';

export const GET_MANAGE_CONFIG_ROW_SELECT_STARTED = 'GET_MANAGE_CONFIG_ROW_SELECT_STARTED';
export const GET_MANAGE_CONFIG_ROW_SELECT_SUCCEEDED = 'GET_MANAGE_CONFIG_ROW_SELECT_SUCCEEDED';
export const GET_MANAGE_CONFIG_ROW_SELECT_FAILED = 'GET_MANAGE_CONFIG_ROW_SELECT_FAILED';

export const GET_CHANGE_NAME = 'GET_CHANGE_NAME';
export const CHANGE_DELETE_DATABASE_SUCCEEDED = 'CHANGE_DELETE_DATABASE_SUCCEEDED';

export const POST_CONFIG_QAM_TABLE_ADD_RANGE = 'POST_CONFIG_QAM_TABLE_ADD_RANGE';
export const DELETE_CONFIGURATION_SUCCESSED = 'DELETE_CONFIGURATION_SUCCESSED';
export const GET_CONFIGURATION_QAM_TABLE_STARTED = 'GET_CONFIGURATION_QAM_TABLE_STARTED';
export const GET_CONFIGURATION_QAM_TABLE_SUCCEEDED = 'GET_CONFIGURATION_QAM_TABLE_SUCCEEDED';
export const GET_CONFIGURATION_QAM_TABLE_FAILED = 'GET_CONFIGURATION_QAM_TABLE_FAILED';

export const DELETE_DATABASE_SUCCEEDED = 'DELETE_DATABASE_SUCCEEDED';
export const ARCHIVE_DATABASE_SUCCEEDED = 'ARCHIVE_DATABASE_SUCCEEDED';

export const UPDATE_CONFIGURATION_SUCCESSED = 'UPDATE_CONFIGURATION_SUCCESSED';











